"""add_chat_sessions_and_messages_tables

Revision ID: 259cf36b3ef4
Revises: 
Create Date: 2025-07-19 16:58:28.134796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "259cf36b3ef4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_sessions",
        sa.Column("user_id", sa.Integer(), nullable=False, comment="사용자 ID"),
        sa.Column("session_id", sa.String(length=50), nullable=False, comment="고유 세션 ID"),
        sa.Column("message_count", sa.Integer(), nullable=True, comment="메시지 개수"),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column("dropped_at", postgresql.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_index("idx_chat_sessions_session_id", "chat_sessions", ["session_id"], unique=False)
    op.create_index("idx_chat_sessions_user_id", "chat_sessions", ["user_id"], unique=False)
    op.create_index(op.f("ix_chat_sessions_id"), "chat_sessions", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_sessions_id"), table_name="chat_sessions")
    op.drop_index("idx_chat_sessions_user_id", table_name="chat_sessions")
    op.drop_index("idx_chat_sessions_session_id", table_name="chat_sessions")
    op.drop_table("chat_sessions")
    # ### end Alembic commands ###
